Repository JuliaManifolds/ManifoldsBase.jl, pull requests merged in 2023-11, with the labels that each got.

#173 Make vee and hat always use real coefficient basis
  NEWS.md
  Project.toml
  src/bases.jl
  test/default_manifold.jl
Labels: preview docs, Ready-for-Review

#174 Pass kwargs in rand on power manifold
  NEWS.md
  Project.toml
  src/PowerManifold.jl
Labels: Ready-for-Review

#175 Fix retarction with t on power manifold
  NEWS.md
  Project.toml
  src/PowerManifold.jl
  test/power.jl
Labels: bug, Ready-for-Review
