Repository JuliaManifolds/ManifoldsBase.jl, pull requests merged in 2023-01, with the labels that each got.

#141 Introduce rand(M) and rand!(M, p) to the API
  Project.toml
  src/DefaultManifold.jl
  src/ManifoldsBase.jl
  src/PowerManifold.jl
  src/decorator_trait.jl
  src/nested_trait.jl
  test/default_manifold.jl
  test/passthrough_decorator.jl
  test/power.jl
Labels: preview docs, Ready-for-Review

#142 Basic definitions for metrics
  Project.toml
  docs/src/manifolds.md
  src/ManifoldsBase.jl
  src/metric.jl
  test/metric.jl
  test/runtests.jl
Labels: preview docs

#145 Introduce the idea of the more-precise default functions from (#144).
  Project.toml
  docs/src/design.md
  src/PowerManifold.jl
  src/decorator_trait.jl
  src/retractions.jl
  src/vector_transport.jl
Labels: Ready-for-Review
