Repository JuliaManifolds/ManifoldsBase.jl, pull requests merged in 2023-08, with the labels that each got.

#160 Add interface for optionally static size
  Project.toml
  src/DefaultManifold.jl
  src/maintypes.jl
  test/default_manifold.jl
Labels: preview docs

#163 Introduce the Weingarten map.
  NEWS.md
  Project.toml
  src/DefaultManifold.jl
  src/ManifoldsBase.jl
  test/default_manifold.jl
  test/test_sphere.jl
Labels: preview docs, Ready-for-Review

#165 Add Weingarten to decorated functions.
  NEWS.md
  Project.toml
  src/decorator_trait.jl
Labels: Ready-for-Review
