Repository JuliaManifolds/ManifoldsBase.jl, pull requests merged in 2024-10, with the labels that each got.

#205 Basis number system swap
  NEWS.md
  Project.toml
  ext/ManifoldsBaseQuaternionsExt.jl
  src/DefaultManifold.jl
  src/bases.jl
  test/ManifoldsBaseTestUtils.jl
  test/allocation.jl
  test/bases.jl
  test/default_manifold.jl
Labels: Ready-for-Review

#206 Introduce r-norms on manifolds with components
  NEWS.md
  Project.toml
  src/DefaultManifold.jl
  src/ManifoldsBase.jl
  src/PowerManifold.jl
  src/ProductManifold.jl
  test/ManifoldsBaseTestUtils.jl
  test/default_manifold.jl
  test/empty_manifold.jl
  test/power.jl
  test/product_manifold.jl
Labels: preview docs, Ready-for-Review

#207 Make `has_components` a decorator function.
  NEWS.md
  Project.toml
  src/decorator_trait.jl
Labels: Ready-for-Review

#209 Pointless norm on vector fibers
  NEWS.md
  Project.toml
  src/VectorFiber.jl
  test/fibers.jl
Labels: enhancement, preview docs, Ready-for-Review
