Repository JuliaManifolds/ManifoldsBase.jl, pull requests merged in 2025-02, with the labels that each got.

#221 🎆 Prepare for ManifoldsBase.jl 1.0
  .github/workflows/documenter.yml
  NEWS.md
  Project.toml
  docs/Project.toml
  docs/src/design.md
  docs/src/types.md
  ext/ManifoldsBaseRecursiveArrayToolsExt/ProductManifoldRecursiveArrayToolsExt.jl
  src/ManifoldsBase.jl
  src/PowerManifold.jl
  src/ProductManifold.jl
  src/ValidationManifold.jl
  src/decorator_trait.jl
  src/exp_log_geo.jl
  src/numerical_checks.jl
  src/parallel_transport.jl
  src/point_vector_fallbacks.jl
  src/retractions.jl
  src/vector_spaces.jl
  src/vector_transport.jl
  test/ManifoldsBaseTestUtils.jl
  test/decorator_traits.jl
  test/default_manifold.jl
  test/deprecated.jl
  test/embedded_manifold.jl
  test/empty_manifold.jl
  test/manifold_fallbacks.jl
  test/passthrough_decorator.jl
  test/power.jl
  test/product_manifold.jl
  test/validation_manifold.jl
  test/vector_transport.jl
  tutorials/Project.toml
  tutorials/_quarto.yml
  tutorials/implement-a-manifold.qmd
Labels: preview docs, breaking

#222 Adapt Tutorial to ManifoldsBase 1.0
  NEWS.md
  tutorials/implement-a-manifold.qmd
Labels: documentation, preview docs, Ready-for-Review

#223 Fix exp_fused allocation
  NEWS.md
  Project.toml
  src/exp_log_geo.jl
  test/default_manifold.jl
Labels: Ready-for-Review
